### ISSUE TITLE
Configurability for new smoke tests

### ISSUE THREAD

**Issue by Vishanth** [abhishek0198/wso2dockerfiles-test-framework#6] opened 2016-08-10 06:24 UTC
I see that when you add a new smoke test for a new product, we have to modify the "smoke-test-runner.go", which in my opinion is not the right thing to do so. Rather we can have a config file to mention the smoke test that are needed to be tested, and programmatically call them from smoke-test-runner class.

**Comment by abhishek0198** [comment] 2016-08-19 03:58
Duplicate of issue#13 raised by Imesh [1]. Closing this one.

[1]. https://github.com/abhishek0198/wso2dockerfiles-test-framework/issues/13

**Closed by abhishek0198** 2016-08-19 03:58 UTC
